export const SIGNUPREQUEST ="SIGNUPREQUEST";
export const SIGNUPSUCCESS ="SIGNUPSUCCESS";
export const SIGNUPFAILURE ="SIGNUPFAILURE";
export const SIGNINSUCCESS ="SIGNINSUCCESS";
export const SIGNINREQUEST ="SIGNINREQUEST";
export const SIGNINFAILURE ="SIGNINFAILURE";